feat: полная карточка билета
alyonastartseva/airways-3 pull request #12
Opened 2024-07-08 10:17 UTC by bullscin

2024-07-08 10:42 UTC, unoejk approved these changes
Смущает только что закрывается карточка по клику на неё же
И не очевидно что левую часть можно скролить - на исходном дизайне там вроде кнопка для раскрытия, которая даёт понять об этом
А так хорошо

2024-07-08 14:30 UTC, DmitryBartoshkin requested changes
Основное замечание, что при клике на билет от раскрывается, а при клике на открытом билете, он снова закрывается. Получается, что я не могу кнопку нажать или получить доп. инфу при клике на иконку возле модели самолёта. Может лучше сделать раскрытие и закрытие при клике на кнопку с количесвом пересадок?

Соглашусь с Лёней, не понятно, что левую часть с инфом можно скролить вниз. На макете есть доп кнопка + градиет, при котором текст постепенно скрывается. Возможно, как вариант, нужно сделать отображаемый скрол рядом с этим блоком, но это больше вопрос к дизайну

Из мелкого, лейбл Самый быстрый я бы сместил влево на толщину бордера

Но в целом выглядит хорошо, молодец)

2024-07-08 14:30 UTC, DmitryBartoshkin commented on src/components/Ticket/CardTicket/CardTicket.tsx
> +        {/* Прайсs */}
Пробегись по коду и комменты подчисти

2024-07-08 14:30 UTC, DmitryBartoshkin commented on src/components/Ticket/TicketFlightInfo/TicketFlightInfo.module.scss
> +      background-color: #f6f8fc;
Ты уже выносил цвета в переменные, тогда и этот нужно добавить для красоты) + далее по файлу посмотреть

2024-07-08 14:30 UTC, DmitryBartoshkin commented on src/components/Ticket/TicketFlightInfo/TicketFlightInfo.tsx
> +            {!fullCard && <AirplaneTakeoffIcon color="#808080" size={20} />}
Пожалуй нужно стили вынести в файл стилей

2024-07-08 14:30 UTC, DmitryBartoshkin commented on src/components/Ticket/TicketPricing/TicketPricing.tsx
> +        <h3 className={scss['ticket__tariff-title']}>Эконом Стандар</h3>
Опечатка СтандарТ

2024-07-08 14:30 UTC, DmitryBartoshkin commented on src/components/Ticket/TicketPricing/TicketPricing.tsx
> +export default TicketPricing;
Имеет смысл каждый тариф вынести в отдельный компонент и их переиспользовать, т.к. данные +- одинаковые, а сейчас много кода

2024-07-08 14:45 UTC, bullscin commented on src/components/Ticket/TicketFlightInfo/TicketFlightInfo.tsx
> +            {!fullCard && <AirplaneTakeoffIcon color="#808080" size={20} />}
Это пропсы компонента, чтобы можно было менять цвет и размер и переиспользовать.

2024-07-08 14:47 UTC, bullscin commented on src/components/Ticket/TicketPricing/TicketPricing.tsx
> +export default TicketPricing;
Думал об этом, но так и не решил стоит это сделать в рамках задачи или уже делать когда будет добавляться взаимодействие с сервером.

2024-07-08 14:51 UTC, DmitryBartoshkin commented on src/components/Ticket/TicketFlightInfo/TicketFlightInfo.tsx
> +            {!fullCard && <AirplaneTakeoffIcon color="#808080" size={20} />}
Оки, но этот цвет здесь прям глаз режет. Давай его хоть в переменную, часто дублируется

2024-07-08 14:53 UTC, DmitryBartoshkin commented on src/components/Ticket/TicketPricing/TicketPricing.tsx
> +export default TicketPricing;
Я думаю, что это лучше на этапе вёрстке сделать, а то х2 работы потом будет

2024-07-08 16:30 UTC, Lartwoods reviewed
только обозначить, что  карточку можно скролить, и сделать закрытие по нажатию вне карточки, в остальном всё красиво

2024-07-09 11:48 UTC, DmitryBartoshkin approved these changes
При наведении курсора на левую колонку, которая прокручивается вниз, прыгает ширина столбца
Название города Санкт-Петербург переносится и образуется большой отступ снизу, также в макете в одну строку
По коду, прям стало намного лучше, класс!

2024-07-09 11:48 UTC, DmitryBartoshkin commented on src/styles/variables.scss
> +  --color-orange: rgb(255, 153, 31);
В названии переменной лучше не писать название цвета, а место или элемент, где он используется

2024-07-09 14:22 UTC, Navse-Jlia approved these changes

2024-07-10 15:41 UTC, alyonastartseva approved these changes

2024-07-10 20:48 UTC, merged