Feature/seats category with api
alyonastartseva/airways-3 pull request #14
Opened 2024-07-09 21:05 UTC by unoejk

Для классов сидений предусмотрен переводчик seatCategory в src/constants/constants.ts
Там массив объектов типа { ru: 'Бизнес', eng: 'BUSINESS' },
С сервера получаем BUSINESS, выводим Бизнес, для этого нужен

Было:
При выборе категории мест информация бралась полностью с переводчика

Стало:
Информация берётся с сервера, но перевод всё ещё ищется на фронте, так как сервер даёт только английскую версию

Как работает:
src/store/services/seatCategories.ts - делает Query
src/hooks/useSeatCategories.ts - получает из Query категории, ищет соответствия в переводчике, не нашёл - вовращает вариант с сервера вместо перевода
src/common/SeatCategory - единственный кто использует этот хук, возвращает список <option> для селекторов. Раньше несколько компонентов этот переводчик использовали, но все option были. Объеденил и поудалял лишнее.

Больше негде использовать, только в option. Вкладка /flight-seats из своего запроса те-же категории получает, им мой не нужен.
Смысла задачи особо не понял, но сделал, наверное на вырост.

2024-07-10 10:10 UTC, DmitryBartoshkin approved these changes
Всё оки, не забудь комменты подчистить

2024-07-10 21:43 UTC, bullscin approved these changes
В целом всё окей. Молодец!

2024-07-10 21:43 UTC, bullscin commented on src/hooks/useSeatCategories.ts
> +      apiSeatCategoriesArr.data.content.forEach(
Я бы использовал map. Сразу вернется новый массив, исключает необходимость вручную добавлять элементы.  Код  будет лаконичнее.

2024-07-11 08:47 UTC, Navse-Jlia approved these changes
молодец

2024-07-16 15:38 UTC, alyonastartseva requested changes

2024-07-16 22:36 UTC, unoejk reviewed
а зачем undefined
    - убрал
    
{ ru: string; eng: string } - используется в нескольких местах, давай вынесем в отдельный интерфейс
    - после правок используется только в одном месте
    
never?
    - после правок пропал из когда
    
давай уберем constSeatCategory - пусть всё будет на английском
    - сделал теперь вместо { ru: string; eng: string } записывается { id: number; categoryType: string } - это с таком виде приходит от сервера; и отображается теперь английское categoryType
    
как будто бы форматирование поехало
    - попраил, преттир работает, незнаю как в таком виде залетело

2024-07-17 18:10 UTC, alyonastartseva approved these changes

2024-07-17 18:27 UTC, merged