feat: completion of authorization
alyonastartseva/airways-3 pull request #27
Opened 2024-08-11 19:11 UTC by Binatik

2024-08-12 15:53 UTC, dajiquwe approved these changes

2024-08-12 17:02 UTC, Binatik commented on src/common/WebsiteLogo/WebsiteLogo.tsx
> -        style={{ color: color, fontSize: isFooter ? '1rem' : '1.25rem' }}
Понимаю, я и сам против подхода такой стилизации но в данном случае это может смотреться более менее ок.

Однако это и вовсе не мой  компонент и я просто его заставил работать хоть как-то а так мне в целом он не нравится и нужна таска на рефактор данного компонента. 

Компонент имеет странные props по типа isFooter и другие. Такой легкий и простой UI компонентик не исполняет ui предназначение а кажется пытается владеть бизнесом что не есть хорошо.

2024-08-12 17:07 UTC, Binatik commented on src/store/services/aircraft.ts
> +        const aircraft = responseAircraft.data as IAircraft;
Использование QueryReturnValue на прямую плохая идея и из за этого у многих даже случилась ошибка.

Решено отказаться от QueryReturnValue и сделать просто хотя бы на коленке каст ``aircraftId``

2024-08-12 17:11 UTC, dajiquwe approved these changes

2024-08-13 05:29 UTC, mihailig0revich approved these changes

2024-08-13 09:29 UTC, AnastasiaSokolina approved these changes

2024-08-14 06:06 UTC, alyonastartseva requested changes

2024-08-14 06:06 UTC, alyonastartseva commented on src/main.tsx
> -import { ChakraProvider } from '@chakra-ui/react';
для будущего: тащить в PR то, что не касается текущей задачи - bad practice
в случае, если нужно будет откатить потом какую-то задачу - будет больно

2024-08-14 06:06 UTC, alyonastartseva commented on src/main.tsx
> -import { ChakraProvider } from '@chakra-ui/react';
функционал чакры не выпиливаем до момента, пока не будут переписаны компоненты на AntD

2024-08-14 06:06 UTC, alyonastartseva commented on src/theme.utils.ts
> +// import { extendTheme } from '@chakra-ui/react';
см коммент выше

2024-08-14 06:06 UTC, alyonastartseva commented on src/hooks/useResizeObserver/useResizeObserver.ts
> +//Отслеживаем размеры ref элемента используя ResizeObserver.
такие комментария лучше удалять - хук сам себя описывает

2024-08-14 06:06 UTC, alyonastartseva commented on src/utils/constants.ts
> +export const word = {
1) **word** - не совсем понятно, что за word
2) почему константы в утилитах?
3) эта константа нужна только для  Header'а, поэтому лучше положить рядом с компонентой, а не на shared-слое

2024-08-15 05:34 UTC, alyonastartseva requested changes

2024-08-15 05:34 UTC, alyonastartseva commented on package.json
> +    "classnames": "^2.5.1",
не поправлено

2024-08-15 05:34 UTC, alyonastartseva commented on src/components/Header/Constants.ts
> +    id: 'x',
давай id как пути назовем - "passengers" и т.д

2024-08-15 05:34 UTC, alyonastartseva commented on src/components/Header/Constants.ts
файлы констант, типов, утилиток компоненты принято называть с маленькой буквы

2024-08-15 05:34 UTC, alyonastartseva commented on src/components/Header/HeaderList/HeaderList.tsx
> +import * as Constants from '../Constants';
import { links } from ''.

2024-08-15 05:34 UTC, alyonastartseva commented on src/components/Header/HeaderList/HeaderList.tsx
> +import { word } from '@/constants';
@/constants/breakpoints.ts

2024-08-15 05:34 UTC, alyonastartseva commented on src/components/Header/HeaderList/HeaderList.tsx
> +import { word } from '@/constants';
импорт можно через index-файл сделать и тогда будет @/constants

2024-08-15 05:34 UTC, alyonastartseva commented on src/components/Header/HeaderList/HeaderList.tsx
> +      {sizeRef.width < Number(word.size_width_xl) ? (
size_width_xl - UPPERCASE

2024-08-15 05:34 UTC, alyonastartseva commented on src/components/Header/HeaderList/HeaderList.tsx
> +      {sizeRef.width < Number(word.size_width_xl) ? (
конвертация в число? сразу число не можем в константе хранить?

2024-08-15 05:34 UTC, alyonastartseva commented on src/constants/constants.ts
> +  size_width_xl: '1200',
ответила выше

2024-08-15 05:34 UTC, alyonastartseva commented on src/constants/constants.ts
> +  me_login: 'Вход',
непонятно зачем в константу

2024-08-15 05:34 UTC, alyonastartseva commented on src/constants/constants.ts
> +  route_admin: '/admin',
если хочешь выносить роуты в константу, то выноси её отдельно и называй ROUTES

2024-08-15 05:34 UTC, alyonastartseva commented on src/constants/constants.ts
> +export const word = {
писала в mattermost, что всё хранить в одном объекте - плохая практика
сейчас и брейкпоинты, и роуты, и кнопки смешаны

2024-08-16 10:06 UTC, alyonastartseva approved these changes

2024-08-16 15:24 UTC, merged