Feature/dark theme
alyonastartseva/airways-3 pull request #3
Opened 2024-06-26 22:06 UTC by Navse-Jlia

темная тема

2024-06-27 04:03 UTC, bullscin requested changes
При изменение на темную тему в формах не видно крестика, кнопка сохранить белая и не видно текста. 

Формы:
-Добавить пасажира
-Добавить самолет
-Добавить пункт назначения
-Добавить часовой пояс
-Забронировать
-Добавить посадочное место

2024-06-27 07:50 UTC, unoejk requested changes
Как Витя написал - кресты на формах, ну и сами формы.
Ещё hover на пагинации плохо виден.
Больше ничего не нашел.

2024-06-27 11:59 UTC, unoejk approved these changes

2024-06-27 12:42 UTC, Lartwoods approved these changes
единственное цвета в стилях можно вынести в переменные, а так очень красиво всё

2024-06-27 17:16 UTC, DmitryBartoshkin requested changes
Тестирую в Firefox 127.0.2
Что заметил:
1. На главной странице - стрелочка смены направлений осталась чёрной и теряется
2. На главной - когда пытаюсь написать город вылета в полях Куда / Откуда, в предлагаемых вариантах городов прозрачный фон и вижу текст под списком. При наведени всё ок. Когда выбираю город из предложенных, цвет шрифта тёмный, сливается
3. На страницах где есть кнопка что-то добавить - открывается форма в светлом оформлении. Может так и нужно, на твоё усморение)

2024-06-27 17:29 UTC, DmitryBartoshkin reviewed
В общем классно, молодец

2024-06-27 17:29 UTC, DmitryBartoshkin commented on src/common/Calendar/Calendar.tsx
> +                                      ? '#000000'
Вложенные тернарники в тернарники, такое себе

2024-06-27 17:29 UTC, DmitryBartoshkin commented on src/common/Pagination/Pagination.scss
> +      color: #fff !important;
Лучше избегать !important по возможности

2024-06-27 21:09 UTC, Navse-Jlia commented on src/common/Calendar/Calendar.tsx
> +                                      ? '#000000'
они вложены , потому что в зависимости от theme цвет должен как то меняться )

2024-06-27 21:12 UTC, Navse-Jlia commented on src/common/Pagination/Pagination.scss
> +      color: #fff !important;
тут используется  !important , потому что к каким то определенным компонентом применялись стили из библиотеки chackra ui(вроде так называется ) и это было прям необходимо

2024-06-28 01:41 UTC, DmitryBartoshkin approved these changes

2024-06-28 06:50 UTC, bullscin approved these changes
Ошибок не нашел.

2024-07-01 01:39 UTC, alyonastartseva requested changes

2024-07-01 01:39 UTC, alyonastartseva commented on src/components/Header/Header.module.scss
> +    // Стили для темной темы
такие комменты лучше подчищать - название говорит само за себя

2024-07-01 01:39 UTC, alyonastartseva commented on src/components/Header/Header.module.scss
> +    // Стили для темной темы
проверь, плиз, в других местах, где указываешь комменты

2024-07-01 01:40 UTC, alyonastartseva commented
красиво 💯 
но очень хочется добавить переменных для цветов

2024-07-04 08:20 UTC, alyonastartseva requested changes

2024-07-04 08:20 UTC, alyonastartseva commented on src/variables.scss
> +:root {
переменные цветов обычно выносят в src/styles/variables

2024-07-04 08:20 UTC, alyonastartseva commented on src/variables.scss
> +:root {
через синтаксис $ scss не захотела ?

2024-07-04 08:20 UTC, alyonastartseva commented on src/components/Footer/Footer.module.scss
> +    background-color: #3b3a3a;
пробегись, плиз, и проверь, что везде (в твоих изменённых файлах) используются переменные

2024-07-04 17:39 UTC, Navse-Jlia commented on src/variables.scss
> +:root {
неа , захотела так попробовать- критично?

2024-07-06 05:29 UTC, alyonastartseva approved these changes

2024-07-06 10:49 UTC, merged