style: responsive design of the homepage
alyonastartseva/airways-3 pull request #30
Opened 2024-08-13 17:33 UTC by AnastasiaSokolina

адаптивный дизайн был выполнен начинающим дизайнером Анастасией (он прост как сибирский валенок)

2024-08-13 17:37 UTC, AnastasiaSokolina commented on src/components/SearchTickets/SearchTickets.tsx
> +          <Row className="show-image" justify="center" align="middle">
Была сохранена изначальная верстка, встроенные разработчиком до меня стили я предпочла не трогать, а только изменять

2024-08-13 17:38 UTC, AnastasiaSokolina commented on src/store/services/aircraft.ts
> +        const aircraft = responseAircraft.data as IAircraft;
Не относится непосредственно к моей задаче, спасибо Сергею, без него все пушилось ломано!

2024-08-13 17:40 UTC, AnastasiaSokolina commented on package-lock.json
Были правки по поводу того, что не стоит коммитить package-lock.json, yarn.lock и т.д., но я не понимаю, как их пропустить, если коммит выполняется через готовую команду

2024-08-13 17:43 UTC, Binatik approved these changes

2024-08-15 06:15 UTC, dajiquwe approved these changes

2024-08-16 10:23 UTC, alyonastartseva requested changes

2024-08-16 10:23 UTC, alyonastartseva commented on src/components/SearchTickets/SearchTickets.scss
> +  @media (max-width: 767px) {
media лучше в конце прописывать (тогда путаницы не будет)

2024-08-18 09:55 UTC, closed without merging