Av-134 LoginAdminForm to Antd
alyonastartseva/airways-3 pull request #34
Opened 2024-08-14 16:11 UTC by dajiquwe

2024-08-14 17:40 UTC, Binatik requested changes

2024-08-14 17:40 UTC, Binatik commented on src/components/LoginAdminForm/LoginAdminForm.module.scss
> +  border-radius: 0.5rem;
Все писать в rem странная затея. Зачем например border-radius rem? (может я чего-то не понимаю) ?

2024-08-14 17:40 UTC, Binatik commented on src/components/LoginAdminForm/LoginAdminForm.module.scss
> +.wrapper {
wrapper лучше называть container.

Еще название class  главному блоку лучше называть как звучит сам компонент.  Тогда выходит и ``container`` нам не нужен.

2024-08-14 17:40 UTC, Binatik commented on src/components/LoginAdminForm/LoginAdminForm.tsx
> +    const a = JSON.stringify(data);
Это как называется?:

any буквально кричит что ты игнорируешь типизацию. Не знаешь какой тип, поставь `unknown`
``const a = JSON.stringify(data); // А чего не Б?``

2024-08-14 17:40 UTC, Binatik commented on src/components/LoginAdminForm/LoginAdminForm.tsx
>      <>
Не нужен ``<></>``

2024-08-14 17:41 UTC, Binatik commented
Давай ты поработаешь над названием классов, это ужасные название, мне не нравится. 

Пример названий: 
```js
<div class="ConvoMessage__bottomInfo">
            <span class="ConvoMessage__time">
              {message.updatedAt && (lang.use('me_edited_label') + ' · ')}
              {lang
                .dateTimeFormatter({ hour: '2-digit', minute: '2-digit' })
                .format(message.sentAt)}
            </span>
            <span class="ConvoMessage__status">{renderReadStatus()}</span>
          </div>
```

2024-08-14 17:42 UTC, Binatik commented
Давай ты избавишься от хардкорных строк  и нескольких овер хедов? (Не обязательно но желательно)

2024-08-14 20:24 UTC, Binatik approved these changes

2024-08-15 17:41 UTC, AnastasiaSokolina approved these changes

2024-08-16 10:28 UTC, alyonastartseva requested changes

2024-08-16 10:28 UTC, alyonastartseva commented on src/components/LoginAdminForm/LoginAdminForm.module.scss
> +.LoginAdminForm {
надо привести к одному стилю нейминг классов (сейчас PascalCase и camelCase)
обычно делают camelCase

2024-08-16 10:28 UTC, alyonastartseva commented on src/components/LoginAdminForm/LoginAdminForm.module.scss
> +  border: 0.0625rem solid #d9d9d9;
все цвета в переменные выносить

2024-08-16 10:28 UTC, alyonastartseva commented on src/components/LoginAdminForm/LoginAdminForm.tsx
> +  setIsAdmin(false);
давай уберем перед мержем

2024-08-16 10:28 UTC, alyonastartseva commented on src/components/LoginAdminForm/LoginAdminForm.tsx
> +                style={{ borderColor: mutation.isError ? 'red' : 'inherit' }}
а зачем?

2024-08-16 10:28 UTC, alyonastartseva commented on src/components/LoginAdminForm/LoginAdminForm.tsx
> +              <Input
в Анте есть Input.Password

2024-08-16 15:22 UTC, alyonastartseva requested changes

2024-08-16 15:22 UTC, alyonastartseva commented on src/components/LoginAdminForm/LoginAdminForm.module.scss
> +  --container-border: #d9d9d9;
см. `src/styles/variables`

2024-08-16 15:22 UTC, alyonastartseva commented on src/components/LoginAdminForm/LoginAdminForm.tsx
> +type LoginAdminForm = {
в проекте используются interface - давай под общую стайл-гайд проекта подстроимся, плиз - заменим на интерфейс

2024-08-16 17:01 UTC, merged