fix: tickets page
alyonastartseva/airways-3 pull request #35
Opened 2024-08-15 14:19 UTC by dajiquwe

2024-08-15 17:50 UTC, AnastasiaSokolina approved these changes

2024-08-16 16:08 UTC, Binatik requested changes

2024-08-16 16:08 UTC, Binatik commented on src/components/Admin/Tickets/Tickets.tsx
> +        <HeaderTable<ITicketsPost> heading=" " formName={EModalNames.TICKETS} />
Почему ``heading=" "`` ? Дай тогда хоть какую-то заглушку и объясни это комментом в github.

``if (Array.isArray(tickets) && !tickets?.length)`` - выглядит не очень, получается tickets может быть не tickets ? То есть название tickets но может прилететь не tickets? А что тогда прилетает сюда еще? 

Билетов может действительно не быть но tickets тоже может не быть разве?: Лучше изменить проверку на то что tickets всегда есть но в нем пока нет билетов. То есть он пустой.

2024-08-16 16:08 UTC, Binatik commented on src/pages/Admin/Tickets/Tickets.page.tsx
>      <>
Зачем React.Fragment? https://react.dev/reference/react/Fragment

``export const TicketsPage = () => {...}``

Если у нас возвращается всего один элемент в разметки и он не многопропсный то скобки не нужны и все помещается в одну строку.

2024-08-16 16:25 UTC, dajiquwe commented on src/components/Admin/Tickets/Tickets.tsx
> +        <HeaderTable<ITicketsPost> heading=" " formName={EModalNames.TICKETS} />
пустой heading нужен чтоб не отображать текст сбоку в хедер тейбле, вообще эт не мой компонент я его особо менять не хотел, моя задача только отобразить кнопку на экране

2024-08-16 18:02 UTC, dajiquwe commented on src/pages/Admin/Tickets/Tickets.page.tsx
>      <>
убрал фрагмент сделал в 1 строчку

2024-08-16 18:24 UTC, Binatik approved these changes

2024-08-19 08:30 UTC, alyonastartseva approved these changes

2024-08-20 03:49 UTC, merged