Верстка карточки билета
alyonastartseva/airways-3 pull request #4
Opened 2024-06-27 07:49 UTC by bullscin

2024-06-27 10:24 UTC, unoejk requested changes
Я тут очень сильно запутался.

Это поидее не должно лежать в pages, а должно быть в components.
Тоесть в pages это такие посредники от роутера которые ссылаются на компоненты, один из которых ты рисуешь.

Сейчас для отображения билетов используется 'src\pages\Admin\Tickets' который ссылается на 'src\components\Admin\Tickets'.
В последнем сейчас лежит страшная таблица, которую по идее и надо перерисовать.

Ещё меня смущает слово Admin в путях, вот этого я не понял.

И надо уточнить нужно ли на тебе на месте переформатировать время из пропсов, MSK в Москва и т.д.
Или это будет отдельной задачей.

- ticket__tariff  лучше сделать кнопкой и добавить hover если оно нажимаемое
- большинство p лучше на span заменить, воде даже все, которые нельзя назвать абзацем

2024-06-27 11:14 UTC, Navse-Jlia approved these changes
по мне (очень хорошо )
я думаю потом в ходе еще можно будет если что , что то поправить 
а так задача выполнена

2024-06-27 12:26 UTC, Lartwoods approved these changes
выглядит хорошо, курсор только добавить при наведении на тарифы и выбор рейсов можно. Думаю, про форматирование времени это другая задача уже

2024-06-27 19:30 UTC, DmitryBartoshkin requested changes
Мне понравилось как свёрстано. При исполнении озвученных замечаний особых претензий нет.
Из моментов:
1. Хочется сменить курсор на руку при наведении на билет, раз уж он разворачивается
2. Вместо названия городов показывает string, нужно проверить
3. Обязательно перенести компонент из Pages

2024-06-27 22:06 UTC, bullscin commented
> Я тут очень сильно запутался.
> 
> Это поидее не должно лежать в pages, а должно быть в components. Тоесть в pages это такие посредники от роутера которые ссылаются на компоненты, один из которых ты рисуешь.
> 
> Сейчас для отображения билетов используется 'src\pages\Admin\Tickets' который ссылается на 'src\components\Admin\Tickets'. В последнем сейчас лежит страшная таблица, которую по идее и надо перерисовать.
> 
> Ещё меня смущает слово Admin в путях, вот этого я не понял.
> 
> И надо уточнить нужно ли на тебе на месте переформатировать время из пропсов, MSK в Москва и т.д. Или это будет отдельной задачей.
> 
> * ticket__tariff  лучше сделать кнопкой и добавить hover если оно нажимаемое
> * большинство p лучше на span заменить, воде даже все, которые нельзя назвать абзацем

2024-06-28 00:29 UTC, unoejk approved these changes

2024-06-28 01:40 UTC, DmitryBartoshkin approved these changes

2024-07-01 01:33 UTC, alyonastartseva requested changes

2024-07-01 01:33 UTC, alyonastartseva commented on src/components/Ticket/CardTicket/CardTicket.module.scss
> +  // Header
такие комменты лучше подчищать - название говорит само за себя

2024-07-01 01:33 UTC, alyonastartseva commented on src/components/Ticket/CardTicket/CardTicket.tsx
> +/* eslint-disable react/prop-types */
правила еслинта лучше не отключать: либо договариваться с командой убрать это правило, либо писать в соответствии с ним

2024-07-01 01:33 UTC, alyonastartseva commented on src/components/Ticket/CardTicket/CardTicket.tsx
> +      {/* Рубль icon */}
комменты либо подписывать (зачем они), либо вообще убирать

2024-07-01 01:36 UTC, alyonastartseva commented
всё гуд, небольшие правки и будем мержить

2024-07-01 01:50 UTC, bullscin commented on src/components/Ticket/CardTicket/CardTicket.tsx
> +/* eslint-disable react/prop-types */
в данном случае оставить или переписывать?

2024-07-01 11:02 UTC, alyonastartseva approved these changes

2024-07-01 11:15 UTC, merged