Hotfix api404
alyonastartseva/airways-3 pull request #5
Opened 2024-06-27 08:21 UTC by unoejk

Поправил api

Билеты и Бронирование - их на сервере нет, о чём тот и сообщает на запрос. Поправил немного под это компонент Алёрт. Ему теперь можно текст с типом задавать.

Все POST вылетают из за ошибки на сервере. Тут пока ничего ничего не поделать.

Ещё пагинация может выдавать страшные вещи. Алёна сказала её не трогать пока.

2024-06-27 12:02 UTC, Lartwoods approved these changes
у меня всё работает, ноль ошибок, только закомментрованный код почистить, а так вроде всё хорошо

2024-06-27 18:57 UTC, DmitryBartoshkin requested changes
- Все страницы работают, ошибок нет.
- Правда сейчас с пагинацией что-то, выбираю например 2 страницу, а в параметрах урл 3, т.е на единицу больше и видимо данные не все показываются, особенно видно по часовым поясам. Хотя может не к твоей задаче это относится. Вот в коде увидел, что ты убрал -1 и указал на это место. Проверь плиз

2024-06-27 18:57 UTC, DmitryBartoshkin commented on src/components/Admin/Flights/Flights.tsx
> +  } = useFlightsQuery(pageIndex);
Точно ли нужно убирать "-1"?

2024-06-28 01:12 UTC, unoejk commented on src/components/Admin/Flights/Flights.tsx
> +  } = useFlightsQuery(pageIndex);
Привет, да я в маттемосте отписал. Глянь пожалуйста

2024-06-28 01:37 UTC, DmitryBartoshkin approved these changes

2024-06-28 07:10 UTC, bullscin approved these changes

2024-06-28 09:46 UTC, alyonastartseva approved these changes

2024-06-28 09:47 UTC, merged