Rtk request
alyonastartseva/airways-3 pull request #9
Opened 2024-07-02 11:13 UTC by Navse-Jlia

сделала переход на Rtk

2024-07-03 07:21 UTC, unoejk approved these changes

2024-07-03 07:46 UTC, bullscin approved these changes
Так мне все нравится. Не большие детали подправить и всё.

2024-07-03 07:46 UTC, bullscin commented on src/components/Admin/Flights/Flights.tsx
> +      // Создаем копию массива перед сортировкой
по опыту прошлых ревью Алены, стоит подчищать подобные комментария.

2024-07-03 07:46 UTC, bullscin commented on src/store/services/apiSlice.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: 'http://92.118.114.29:8080/api' }),
Здесь лучше импортировать baseURL из src/services/axios.service.ts. Кажется, это единственное место где он определен и будет лучше, чтобы он и оставался в одном месте.

2024-07-03 09:02 UTC, Lartwoods approved these changes
всё супер, нечего добавить, про url отметили

2024-07-03 09:37 UTC, Navse-Jlia commented on src/components/Admin/Flights/Flights.tsx
> +      // Создаем копию массива перед сортировкой
да, ок - не подумала

2024-07-04 09:13 UTC, alyonastartseva requested changes

2024-07-04 09:13 UTC, alyonastartseva commented on src/store/services/apiSlice.ts
> +import { baseURL } from '../../services/axios.service';
давай разделим этом слайc на два - на aircraftSlice и на flightSlice

т.к. если все методы апихи будем сюда добавлять, то получится ооооочень много кода

2024-07-04 09:13 UTC, alyonastartseva commented on src/store/services/apiSlice.ts
> +export const apiSlice = createApi({
ещё давай удалим, плз, старые руки от react-query

2024-07-06 05:32 UTC, alyonastartseva approved these changes

2024-07-06 05:32 UTC, alyonastartseva commented on src/store/services/aircraftSlice.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: baseURL }),
можно просто : { baseUrl }

2024-07-06 10:54 UTC, merged